language: nodeCreate public and private SSH keysjs
nodejs:
- 6.9.1
notifications:
  email:
    onfailure: change
    onsuccess: change
addons:
  sshknownhosts:
  - 167.99.0.204
branches:
  only:
  - master
env:
  global:
  - REMOTEAPPDIR=/srv/www/bywhale.me/
  - REMOTEUSER=deploy
  - REMOTEHOST=167.99.0.204
  - PORT=8080
beforeinstall:
- npm install -g npm@^2
install:
- npm install --only=dev
beforescript:
- chmod 600 deploy && mv deploy ~/.ssh/idrsa
script:
- npm run build
after_success:
- "./scripts/deploy.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_6997cb16d997_key -iv $encrypted_6997cb16d997_iv
  -in deploy.enc -out deploy -d
