language: nodeCreate public and private SSH keysjs
nodejs:
- 9.10.0
notifications:
  email:
    onfailure: change
    onsuccess: change
addons:
  sshknownhosts:
  - 167.99.0.204
cache:
  yarn: true
  directories:
  - node_modules
branches:
  only:
  - master
env:
  global:
  - REMOTEAPPDIR=/srv/www/bywhale.me/
  - REMOTEUSER=deploy
  - REMOTEHOST=167.99.0.204
  - PORT=8080
install:
- yarn install
before_script:
- chmod 600 deploy && mv deploy ~/.ssh/idrsa
script:
- yarn travis
after_success:
- "chmod +x ./scripts/deploy.sh && ./scripts/deploy.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_6997cb16d997_key -iv $encrypted_6997cb16d997_iv
  -in deploy.enc -out deploy -d
